env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_ABI=google_apis/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins

language: android
jdk: oraclejdk8
os: linux
android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    # For Google Maps API v1
    - addon-google_apis-google-$ANDROID_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    
    #system images for emulator
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21

before_install: 
    - chmod +x gradlew
    - pip install --user codecov

after_success:
    - codecov                       #Run codecov
    
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

notifications:
    email: false
    slack: csci4230:k83QeSNRR4R4uDtwGx2FXj2U
    

# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x gradlew      #Grant permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
  - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
  - android-wait-for-emulator             #Run wait for the emulator script.
  - adb devices                           #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace   

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle
